name: CI

on:
  pull_request:
  push:
    tags-ignore:
      - v*

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scalaversion: ["2.11.12", "2.12.10", "2.13.1"]
        scalajsversion: ["1.x", "0.6.x"]
        include:
          - scalaversion: "2.10.7"
            scalajsversion: "0.6.x"
    env:
      SCALAJS_VERSION: "${{ matrix.scalajsversion == '0.6.x' && '0.6.28' || '' }}"
    steps:

      - uses: actions/checkout@v2

      - name: Setup Scala
        uses: japgolly/setup-everything-scala@v1.0

      - name: Hacks for Scala 2.10
        if: matrix.scalaversion == '2.10.7'
        run: ./prepareForScala210.sh

      - name: Build
        run: sbt "++${{ matrix.scalaversion }}" package

      - name: Test generate documentation
        run: sbt "++${{ matrix.scalaversion }}" doc

      - name: Build examples
        run: sbt "++${{ matrix.scalaversion }}" example/compile

      - name: Validate formatting
        run: sbt "++${{ matrix.scalaversion }}" scalafmtCheck

      - name: Validate api report
        if: matrix.scalajsversion == '1.x' && matrix.scalaversion != '2.11.12'
        run: ./api-reports/validate "${{ matrix.scalaversion }}"

  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: japgolly/setup-everything-scala@v1.0
      - name: Readme generation
        run: sbt readme/run
