name: Release
on:
  push:
    branches: ["master", "series/1.x"]
    tags: ["v*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scalajsversion: ["1.x", "0.6.x"]
    env:
      SCALAJS_VERSION: "${{ matrix.scalajsversion == '0.6.x' && '0.6.28' || '' }}"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v13
      - name: Hacks for Scala 2.10
        run: ./prepareForScala210.sh
      - run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
